place = game.PlaceId

if place == 142823291 or place == 96420002244668 or place == 335132309 or place == 636649648 then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/ThatSick/HoneyLua/refs/heads/main/Supported%20Games/Murder%20Mystery%202/Main.luau"))()
elseif place == 920587237 then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/ThatSick/HoneyLua/refs/heads/main/Supported%20Games/Adopt%20Me/Main.luau"))()
end

return
